using System;
using System.Collections.Generic;

namespace AccumapDataProcessor.Models
{
    public partial class TDimAccountFinance
    {
        public string? AccountId { get; set; }
        public string? AccountDescription { get; set; }
        public string? GlAccount { get; set; }
        public string? GlAccountDescription { get; set; }
        public string? MajorAccount { get; set; }
        public string? MinorAccount { get; set; }
        public string? MajorAccountDescription { get; set; }
        public string? MajorClassCode { get; set; }
        public string? ClassCodeDescription { get; set; }
        public string? UnaryOperator { get; set; }
        public string? AccountFormula { get; set; }
        public string? AccountFormulaProperty { get; set; }
        public string? AccountLevel01Formula { get; set; }
        public string? AccountLevel01FormulaProperty { get; set; }
        public string? AccountLevel02Formula { get; set; }
        public string? AccountLevel02FormulaProperty { get; set; }
        public string? AccountLevel03Formula { get; set; }
        public string? AccountLevel03FormulaProperty { get; set; }
        public string? AccountLevel04Formula { get; set; }
        public string? AccountLevel04FormulaProperty { get; set; }
        public string? AccountLevel05Formula { get; set; }
        public string? AccountLevel05FormulaProperty { get; set; }
        public string? AccountLevel06Formula { get; set; }
        public string? AccountLevel06FormulaProperty { get; set; }
        public string? AccountLevel07Formula { get; set; }
        public string? AccountLevel07FormulaProperty { get; set; }
        public string? AccountLevel08Formula { get; set; }
        public string? AccountLevel08FormulaProperty { get; set; }
        public string? AccountLevel09Formula { get; set; }
        public string? AccountLevel09FormulaProperty { get; set; }
        public string? AccountLevel10Formula { get; set; }
        public string? AccountLevel10FormulaProperty { get; set; }
        public string? AccountLevel01Desc { get; set; }
        public string? AccountLevel02Desc { get; set; }
        public string? AccountLevel03Desc { get; set; }
        public string? AccountLevel04Desc { get; set; }
        public string? AccountLevel05Desc { get; set; }
        public string? AccountLevel06Desc { get; set; }
        public string? AccountLevel07Desc { get; set; }
        public string? AccountLevel08Desc { get; set; }
        public string? AccountLevel09Desc { get; set; }
        public string? AccountLevel10Desc { get; set; }
        public string? AccountLevel01SortKey { get; set; }
        public string? AccountLevel02SortKey { get; set; }
        public string? AccountLevel03SortKey { get; set; }
        public string? AccountLevel04SortKey { get; set; }
        public string? AccountLevel05SortKey { get; set; }
        public string? AccountLevel06SortKey { get; set; }
        public string? AccountLevel07SortKey { get; set; }
        public string? AccountLevel08SortKey { get; set; }
        public string? AccountLevel09SortKey { get; set; }
        public string? AccountLevel10SortKey { get; set; }
        public string? DepAccountId { get; set; }
        public string? DepAccountDescription { get; set; }
        public string? DepLevel01Desc { get; set; }
        public string? DepLevel02Desc { get; set; }
        public string? DepLevel03Desc { get; set; }
        public string? DepLevel04Desc { get; set; }
        public string? DepLevel05Desc { get; set; }
        public string? DepLevel01SortKey { get; set; }
        public string? DepLevel02SortKey { get; set; }
        public string? DepLevel03SortKey { get; set; }
        public string? DepLevel04SortKey { get; set; }
        public string? DepLevel05SortKey { get; set; }
        public string? TaxopAccountId { get; set; }
        public string? TaxopAccountDescription { get; set; }
        public string? TaxopLevel01Desc { get; set; }
        public string? TaxopLevel02Desc { get; set; }
        public string? TaxopLevel03Desc { get; set; }
        public string? TaxopLevel04Desc { get; set; }
        public string? TaxopLevel05Desc { get; set; }
        public string? TaxopLevel01SortKey { get; set; }
        public string? TaxopLevel02SortKey { get; set; }
        public string? TaxopLevel03SortKey { get; set; }
        public string? TaxopLevel04SortKey { get; set; }
        public string? TaxopLevel05SortKey { get; set; }
        public string? GcartAccountId { get; set; }
        public string? GcartAccountDescription { get; set; }
        public string? GcartLevel01Desc { get; set; }
        public string? GcartLevel02Desc { get; set; }
        public string? GcartLevel03Desc { get; set; }
        public string? GcartLevel04Desc { get; set; }
        public string? GcartLevel05Desc { get; set; }
        public string? GcartLevel01SortKey { get; set; }
        public string? GcartLevel02SortKey { get; set; }
        public string? GcartLevel03SortKey { get; set; }
        public string? GcartLevel04SortKey { get; set; }
        public string? GcartLevel05SortKey { get; set; }
        public string? EstmaAccountId { get; set; }
        public string? EstmaAccountDescription { get; set; }
        public string? EstmaLevel01Desc { get; set; }
        public string? EstmaLevel02Desc { get; set; }
        public string? EstmaLevel03Desc { get; set; }
        public string? EstmaLevel04Desc { get; set; }
        public string? EstmaLevel05Desc { get; set; }
        public string? EstmaLevel01SortKey { get; set; }
        public string? EstmaLevel02SortKey { get; set; }
        public string? EstmaLevel03SortKey { get; set; }
        public string? EstmaLevel04SortKey { get; set; }
        public string? EstmaLevel05SortKey { get; set; }
    }
}
