using System;
using System.Collections.Generic;

namespace AccumapDataProcessor.Models
{
    public partial class TDimAccountFinance20200622
    {
        public string AccountId { get; set; } = null!;
        public string? AccountDescription { get; set; }
        public string? GlAccount { get; set; }
        public string? GlAccountDescription { get; set; }
        public string? MajorAccount { get; set; }
        public string? MinorAccount { get; set; }
        public string? MajorAccountDescription { get; set; }
        public string? MajorClassCode { get; set; }
        public string? ClassCodeDescription { get; set; }
        public string? UnaryOperator { get; set; }
        public string? AccountLevel01 { get; set; }
        public string? AccountLevel02 { get; set; }
        public string? AccountLevel03 { get; set; }
        public string? AccountLevel04 { get; set; }
        public string? AccountLevel05 { get; set; }
        public string? AccountLevel06 { get; set; }
        public string? AccountLevel07 { get; set; }
        public string? AccountLevel08 { get; set; }
        public string? AccountLevel09 { get; set; }
        public string? AccountLevel10 { get; set; }
        public string? AccountLevel01SortKey { get; set; }
        public string? AccountLevel02SortKey { get; set; }
        public string? AccountLevel03SortKey { get; set; }
        public string? AccountLevel04SortKey { get; set; }
        public string? AccountLevel05SortKey { get; set; }
        public string? AccountLevel06SortKey { get; set; }
        public string? AccountLevel07SortKey { get; set; }
        public string? AccountLevel08SortKey { get; set; }
        public string? AccountLevel09SortKey { get; set; }
        public string? AccountLevel10SortKey { get; set; }
        public string? AccountGroup { get; set; }
        public string? DepAccountGroup { get; set; }
        public string? DepAccountId { get; set; }
        public string? DepAccountDescription { get; set; }
        public string? DepGlAccount { get; set; }
        public string? DepGlAccountDescription { get; set; }
        public string? DepMajorAccount { get; set; }
        public string? DepMinorAccount { get; set; }
        public string? DepMajorAccountDescription { get; set; }
        public string? DepMajorClassCode { get; set; }
        public string? DepClassCodeDescription { get; set; }
        public string? DepUnaryOperator { get; set; }
        public string? DepLevel01 { get; set; }
        public string? DepLevel02 { get; set; }
        public string? DepLevel03 { get; set; }
        public string? DepLevel04 { get; set; }
        public string? DepLevel05 { get; set; }
        public string? DepLevel01SortKey { get; set; }
        public string? DepLevel02SortKey { get; set; }
        public string? DepLevel03SortKey { get; set; }
        public string? DepLevel04SortKey { get; set; }
        public string? DepLevel05SortKey { get; set; }
        public string? TaxopAccountGroup { get; set; }
        public string? TaxopAccountId { get; set; }
        public string? TaxopAccountDescription { get; set; }
        public string? TaxopGlAccount { get; set; }
        public string? TaxopGlAccountDescription { get; set; }
        public string? TaxopMajorAccount { get; set; }
        public string? TaxopMinorAccount { get; set; }
        public string? TaxopMajorAccountDescription { get; set; }
        public string? TaxopMajorClassCode { get; set; }
        public string? TaxopClassCodeDescription { get; set; }
        public string? TaxopUnaryOperator { get; set; }
        public string? TaxopLevel01 { get; set; }
        public string? TaxopLevel02 { get; set; }
        public string? TaxopLevel03 { get; set; }
        public string? TaxopLevel04 { get; set; }
        public string? TaxopLevel05 { get; set; }
        public string? TaxopLevel01SortKey { get; set; }
        public string? TaxopLevel02SortKey { get; set; }
        public string? TaxopLevel03SortKey { get; set; }
        public string? TaxopLevel04SortKey { get; set; }
        public string? TaxopLevel05SortKey { get; set; }
        public string? GcartAccountGroup { get; set; }
        public string? GcartAccountId { get; set; }
        public string? GcartAccountDescription { get; set; }
        public string? GcartGlAccount { get; set; }
        public string? GcartGlAccountDescription { get; set; }
        public string? GcartMajorAccount { get; set; }
        public string? GcartMinorAccount { get; set; }
        public string? GcartMajorAccountDescription { get; set; }
        public string? GcartMajorClassCode { get; set; }
        public string? GcartClassCodeDescription { get; set; }
        public string? GcartUnaryOperator { get; set; }
        public string? GcartLevel01 { get; set; }
        public string? GcartLevel02 { get; set; }
        public string? GcartLevel03 { get; set; }
        public string? GcartLevel04 { get; set; }
        public string? GcartLevel05 { get; set; }
        public string? GcartLevel01SortKey { get; set; }
        public string? GcartLevel02SortKey { get; set; }
        public string? GcartLevel03SortKey { get; set; }
        public string? GcartLevel04SortKey { get; set; }
        public string? GcartLevel05SortKey { get; set; }
        public string? EstmaAccountGroup { get; set; }
        public string? EstmaAccountId { get; set; }
        public string? EstmaAccountDescription { get; set; }
        public string? EstmaGlAccount { get; set; }
        public string? EstmaGlAccountDescription { get; set; }
        public string? EstmaMajorAccount { get; set; }
        public string? EstmaMinorAccount { get; set; }
        public string? EstmaMajorAccountDescription { get; set; }
        public string? EstmaMajorClassCode { get; set; }
        public string? EstmaClassCodeDescription { get; set; }
        public string? EstmaUnaryOperator { get; set; }
        public string? EstmaLevel01 { get; set; }
        public string? EstmaLevel02 { get; set; }
        public string? EstmaLevel03 { get; set; }
        public string? EstmaLevel04 { get; set; }
        public string? EstmaLevel05 { get; set; }
        public string? EstmaLevel01SortKey { get; set; }
        public string? EstmaLevel02SortKey { get; set; }
        public string? EstmaLevel03SortKey { get; set; }
        public string? EstmaLevel04SortKey { get; set; }
        public string? EstmaLevel05SortKey { get; set; }
    }
}
